# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ORS_GUI(object):
    def setupUi(self, ORS_GUI):
        ORS_GUI.setObjectName(_fromUtf8("ORS_GUI"))
        ORS_GUI.resize(730, 566)
        self.centralwidget = QtGui.QWidget(ORS_GUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(580, 430, 91, 51))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.Geography = QtGui.QGroupBox(self.centralwidget)
        self.Geography.setGeometry(QtCore.QRect(20, 250, 281, 271))
        self.Geography.setFlat(False)
        self.Geography.setCheckable(False)
        self.Geography.setObjectName(_fromUtf8("Geography"))
        self.gridLayoutWidget = QtGui.QWidget(self.Geography)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 251, 221))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.map = MapWidget(self.gridLayoutWidget)
        self.map.setFrameShape(QtGui.QFrame.StyledPanel)
        self.map.setFrameShadow(QtGui.QFrame.Raised)
        self.map.setObjectName(_fromUtf8("map"))
        self.gridLayout.addWidget(self.map, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.compass = CompassWidget(self.gridLayoutWidget)
        self.compass.setObjectName(_fromUtf8("compass"))
        self.gridLayout.addWidget(self.compass, 0, 1, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.latiVal = QtGui.QLabel(self.gridLayoutWidget)
        self.latiVal.setObjectName(_fromUtf8("latiVal"))
        self.horizontalLayout_2.addWidget(self.latiVal)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.longLab = QtGui.QLabel(self.gridLayoutWidget)
        self.longLab.setObjectName(_fromUtf8("longLab"))
        self.horizontalLayout_3.addWidget(self.longLab)
        self.longVal = QtGui.QLabel(self.gridLayoutWidget)
        self.longVal.setObjectName(_fromUtf8("longVal"))
        self.horizontalLayout_3.addWidget(self.longVal)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.Environment = QtGui.QGroupBox(self.centralwidget)
        self.Environment.setGeometry(QtCore.QRect(130, 20, 211, 191))
        self.Environment.setObjectName(_fromUtf8("Environment"))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.Environment)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 50, 141, 41))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_18 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_8.addWidget(self.label_18)
        self.label_19 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_8.addWidget(self.label_19)
        self.horizontalLayoutWidget_6 = QtGui.QWidget(self.Environment)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 90, 141, 41))
        self.horizontalLayoutWidget_6.setObjectName(_fromUtf8("horizontalLayoutWidget_6"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_20 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_9.addWidget(self.label_20)
        self.label_21 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_9.addWidget(self.label_21)
        self.BoatStatus = QtGui.QGroupBox(self.centralwidget)
        self.BoatStatus.setGeometry(QtCore.QRect(360, 10, 351, 351))
        self.BoatStatus.setObjectName(_fromUtf8("BoatStatus"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.BoatStatus)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 331, 161))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.Rudder = QtGui.QGroupBox(self.gridLayoutWidget_2)
        self.Rudder.setObjectName(_fromUtf8("Rudder"))
        self.rPosDial = QtGui.QDial(self.Rudder)
        self.rPosDial.setGeometry(QtCore.QRect(0, 10, 50, 64))
        self.rPosDial.setMaximum(360)
        self.rPosDial.setInvertedAppearance(False)
        self.rPosDial.setInvertedControls(False)
        self.rPosDial.setWrapping(True)
        self.rPosDial.setObjectName(_fromUtf8("rPosDial"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.Rudder)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 70, 161, 81))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_12 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_5.addWidget(self.label_12)
        self.rDstLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.rDstLabel.setObjectName(_fromUtf8("rDstLabel"))
        self.horizontalLayout_5.addWidget(self.rDstLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.rPosLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.rPosLabel.setObjectName(_fromUtf8("rPosLabel"))
        self.horizontalLayout.addWidget(self.rPosLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout_3.addWidget(self.Rudder, 0, 0, 1, 1)
        self.Sail = QtGui.QGroupBox(self.gridLayoutWidget_2)
        self.Sail.setObjectName(_fromUtf8("Sail"))
        self.sPosSlider = QtGui.QSlider(self.Sail)
        self.sPosSlider.setGeometry(QtCore.QRect(10, 30, 141, 29))
        self.sPosSlider.setMaximum(6)
        self.sPosSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sPosSlider.setInvertedAppearance(False)
        self.sPosSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sPosSlider.setObjectName(_fromUtf8("sPosSlider"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.Sail)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 70, 160, 80))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_16 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_7.addWidget(self.label_16)
        self.sDstLabel = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.sDstLabel.setObjectName(_fromUtf8("sDstLabel"))
        self.horizontalLayout_7.addWidget(self.sDstLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_14 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_6.addWidget(self.label_14)
        self.sPosLabel = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.sPosLabel.setObjectName(_fromUtf8("sPosLabel"))
        self.horizontalLayout_6.addWidget(self.sPosLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.gridLayout_3.addWidget(self.Sail, 0, 1, 1, 1)
        self.Hemisphere = QtGui.QGroupBox(self.BoatStatus)
        self.Hemisphere.setGeometry(QtCore.QRect(20, 210, 311, 111))
        self.Hemisphere.setObjectName(_fromUtf8("Hemisphere"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.Hemisphere)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 30, 161, 81))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_10.addWidget(self.label_13)
        self.rDstLabel_2 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.rDstLabel_2.setObjectName(_fromUtf8("rDstLabel_2"))
        self.horizontalLayout_10.addWidget(self.rDstLabel_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_4.addWidget(self.label_8)
        self.rPosLabel_2 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.rPosLabel_2.setObjectName(_fromUtf8("rPosLabel_2"))
        self.horizontalLayout_4.addWidget(self.rPosLabel_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_15 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_11.addWidget(self.label_15)
        self.rDstLabel_3 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.rDstLabel_3.setObjectName(_fromUtf8("rDstLabel_3"))
        self.horizontalLayout_11.addWidget(self.rDstLabel_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.Mode = QtGui.QGroupBox(self.centralwidget)
        self.Mode.setGeometry(QtCore.QRect(10, 20, 111, 191))
        self.Mode.setObjectName(_fromUtf8("Mode"))
        self.verticalLayoutWidget = QtGui.QWidget(self.Mode)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 92, 165))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radioButton = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setCheckable(False)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.verticalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_2.setCheckable(False)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.verticalLayout_2.addWidget(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_3.setCheckable(False)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.verticalLayout_2.addWidget(self.radioButton_3)
        self.radioButton_4 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_4.setCheckable(False)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.verticalLayout_2.addWidget(self.radioButton_4)
        ORS_GUI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ORS_GUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 730, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        ORS_GUI.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ORS_GUI)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ORS_GUI.setStatusBar(self.statusbar)

        self.retranslateUi(ORS_GUI)
        QtCore.QMetaObject.connectSlotsByName(ORS_GUI)

    def retranslateUi(self, ORS_GUI):
        ORS_GUI.setWindowTitle(_translate("ORS_GUI", "ORS_GUI", None))
        self.pushButton.setText(_translate("ORS_GUI", "Launch\nTorpedoes", None))
        self.Geography.setTitle(_translate("ORS_GUI", "Geography", None))
        self.label_3.setText(_translate("ORS_GUI", "--", None))
        self.label_4.setToolTip(_translate("ORS_GUI", "Measured From North, Clockwise", None))
        self.label_4.setText(_translate("ORS_GUI", "Angle", None))
        self.label_2.setText(_translate("ORS_GUI", "Direction:", None))
        self.label_5.setText(_translate("ORS_GUI", "--", None))
        self.label.setText(_translate("ORS_GUI", "Latitude :", None))
        self.latiVal.setText(_translate("ORS_GUI", "--", None))
        self.longLab.setText(_translate("ORS_GUI", "Longitude :", None))
        self.longVal.setText(_translate("ORS_GUI", "--", None))
        self.Environment.setTitle(_translate("ORS_GUI", "Environment", None))
        self.label_18.setText(_translate("ORS_GUI", "WindSpeed :", None))
        self.label_19.setText(_translate("ORS_GUI", "--", None))
        self.label_20.setText(_translate("ORS_GUI", "Wind Direction :", None))
        self.label_21.setText(_translate("ORS_GUI", "--", None))
        self.BoatStatus.setTitle(_translate("ORS_GUI", "Boat Status", None))
        self.Rudder.setTitle(_translate("ORS_GUI", "Rudder", None))
        self.label_12.setText(_translate("ORS_GUI", "Destination :", None))
        self.rDstLabel.setText(_translate("ORS_GUI", "--", None))
        self.label_7.setText(_translate("ORS_GUI", "Position :", None))
        self.rPosLabel.setText(_translate("ORS_GUI", "--", None))
        self.Sail.setTitle(_translate("ORS_GUI", "Sail", None))
        self.label_16.setText(_translate("ORS_GUI", "Destination :", None))
        self.sDstLabel.setText(_translate("ORS_GUI", "--", None))
        self.label_14.setText(_translate("ORS_GUI", "Position :", None))
        self.sPosLabel.setText(_translate("ORS_GUI", "--", None))
        self.Hemisphere.setTitle(_translate("ORS_GUI", "[other Hemisphere stuff]", None))
        self.label_13.setText(_translate("ORS_GUI", "Speed:", None))
        self.rDstLabel_2.setText(_translate("ORS_GUI", "--", None))
        self.label_8.setText(_translate("ORS_GUI", "Angle:", None))
        self.rPosLabel_2.setText(_translate("ORS_GUI", "--", None))
        self.label_15.setText(_translate("ORS_GUI", "Date:", None))
        self.rDstLabel_3.setText(_translate("ORS_GUI", "--", None))
        self.Mode.setTitle(_translate("ORS_GUI", "Mode", None))
        self.radioButton.setText(_translate("ORS_GUI", "Default", None))
        self.radioButton_2.setText(_translate("ORS_GUI", "RC", None))
        self.radioButton_3.setText(_translate("ORS_GUI", "Auto", None))
        self.radioButton_4.setText(_translate("ORS_GUI", "Test", None))

from CompassWidget import CompassWidget
from MapWidget import MapWidget
