# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Tue Feb  2 20:34:34 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ORS_GUI(object):
    def setupUi(self, ORS_GUI):
        ORS_GUI.setObjectName(_fromUtf8("ORS_GUI"))
        ORS_GUI.resize(688, 477)
        self.centralwidget = QtGui.QWidget(ORS_GUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(560, 320, 91, 51))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.Geography = QtGui.QGroupBox(self.centralwidget)
        self.Geography.setGeometry(QtCore.QRect(390, 10, 281, 271))
        self.Geography.setFlat(False)
        self.Geography.setCheckable(False)
        self.Geography.setObjectName(_fromUtf8("Geography"))
        self.gridLayoutWidget = QtGui.QWidget(self.Geography)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 251, 221))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.map = MapWidget(self.gridLayoutWidget)
        self.map.setFrameShape(QtGui.QFrame.StyledPanel)
        self.map.setFrameShadow(QtGui.QFrame.Raised)
        self.map.setObjectName(_fromUtf8("map"))
        self.gridLayout.addWidget(self.map, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.compass = CompassWidget(self.gridLayoutWidget)
        self.compass.setObjectName(_fromUtf8("compass"))
        self.gridLayout.addWidget(self.compass, 0, 1, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.latiVal = QtGui.QLabel(self.gridLayoutWidget)
        self.latiVal.setObjectName(_fromUtf8("latiVal"))
        self.horizontalLayout_2.addWidget(self.latiVal)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.longLab = QtGui.QLabel(self.gridLayoutWidget)
        self.longLab.setObjectName(_fromUtf8("longLab"))
        self.horizontalLayout_3.addWidget(self.longLab)
        self.longVal = QtGui.QLabel(self.gridLayoutWidget)
        self.longVal.setObjectName(_fromUtf8("longVal"))
        self.horizontalLayout_3.addWidget(self.longVal)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.Environment = QtGui.QGroupBox(self.centralwidget)
        self.Environment.setGeometry(QtCore.QRect(130, 20, 211, 191))
        self.Environment.setObjectName(_fromUtf8("Environment"))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.Environment)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 50, 141, 41))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_18 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_8.addWidget(self.label_18)
        self.label_19 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_8.addWidget(self.label_19)
        self.BoatStatus = QtGui.QGroupBox(self.centralwidget)
        self.BoatStatus.setGeometry(QtCore.QRect(10, 220, 351, 201))
        self.BoatStatus.setObjectName(_fromUtf8("BoatStatus"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.BoatStatus)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 331, 161))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.Rudder = QtGui.QGroupBox(self.gridLayoutWidget_2)
        self.Rudder.setObjectName(_fromUtf8("Rudder"))
        self.dial = QtGui.QDial(self.Rudder)
        self.dial.setGeometry(QtCore.QRect(0, 10, 50, 64))
        self.dial.setObjectName(_fromUtf8("dial"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.Rudder)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 70, 161, 81))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_12 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_5.addWidget(self.label_12)
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_5.addWidget(self.label_13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout_3.addWidget(self.Rudder, 0, 0, 1, 1)
        self.Sail = QtGui.QGroupBox(self.gridLayoutWidget_2)
        self.Sail.setObjectName(_fromUtf8("Sail"))
        self.horizontalSlider = QtGui.QSlider(self.Sail)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 30, 141, 29))
        self.horizontalSlider.setMaximum(6)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.Sail)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 70, 160, 80))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_16 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_7.addWidget(self.label_16)
        self.label_17 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_7.addWidget(self.label_17)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_14 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_6.addWidget(self.label_14)
        self.label_15 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_6.addWidget(self.label_15)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.gridLayout_3.addWidget(self.Sail, 0, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 111, 191))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 92, 165))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radioButton = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setCheckable(False)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.verticalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_2.setCheckable(False)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.verticalLayout_2.addWidget(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_3.setCheckable(False)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.verticalLayout_2.addWidget(self.radioButton_3)
        self.radioButton_4 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_4.setCheckable(False)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.verticalLayout_2.addWidget(self.radioButton_4)
        ORS_GUI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ORS_GUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 688, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        ORS_GUI.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ORS_GUI)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ORS_GUI.setStatusBar(self.statusbar)

        self.retranslateUi(ORS_GUI)
        QtCore.QMetaObject.connectSlotsByName(ORS_GUI)

    def retranslateUi(self, ORS_GUI):
        ORS_GUI.setWindowTitle(_translate("ORS_GUI", "ORS_GUI", None))
        self.pushButton.setText(_translate("ORS_GUI", "Launch Boat", None))
        self.Geography.setTitle(_translate("ORS_GUI", "Geography", None))
        self.label_3.setText(_translate("ORS_GUI", "--", None))
        self.label_4.setToolTip(_translate("ORS_GUI", "Measured From North, Clockwise", None))
        self.label_4.setText(_translate("ORS_GUI", "Angle", None))
        self.label_2.setText(_translate("ORS_GUI", "Direction:", None))
        self.label_5.setText(_translate("ORS_GUI", "--", None))
        self.label.setText(_translate("ORS_GUI", "Latitude :", None))
        self.latiVal.setText(_translate("ORS_GUI", "--", None))
        self.longLab.setText(_translate("ORS_GUI", "Longitude :", None))
        self.longVal.setText(_translate("ORS_GUI", "--", None))
        self.Environment.setTitle(_translate("ORS_GUI", "Environment", None))
        self.label_18.setText(_translate("ORS_GUI", "WindSpeed :", None))
        self.label_19.setText(_translate("ORS_GUI", "--", None))
        self.BoatStatus.setTitle(_translate("ORS_GUI", "Boat Status", None))
        self.Rudder.setTitle(_translate("ORS_GUI", "Rudder", None))
        self.label_12.setText(_translate("ORS_GUI", "Destination :", None))
        self.label_13.setText(_translate("ORS_GUI", "--", None))
        self.label_7.setText(_translate("ORS_GUI", "Position :", None))
        self.label_9.setText(_translate("ORS_GUI", "--", None))
        self.Sail.setTitle(_translate("ORS_GUI", "Sail", None))
        self.label_16.setText(_translate("ORS_GUI", "Destination :", None))
        self.label_17.setText(_translate("ORS_GUI", "--", None))
        self.label_14.setText(_translate("ORS_GUI", "Position :", None))
        self.label_15.setText(_translate("ORS_GUI", "--", None))
        self.groupBox.setTitle(_translate("ORS_GUI", "Mode", None))
        self.radioButton.setText(_translate("ORS_GUI", "Default", None))
        self.radioButton_2.setText(_translate("ORS_GUI", "RC", None))
        self.radioButton_3.setText(_translate("ORS_GUI", "Auto", None))
        self.radioButton_4.setText(_translate("ORS_GUI", "Test", None))

from CompassWidget import CompassWidget
from MapWidget import MapWidget
